### ISSUE TITLE
Picking a persistent URL for this ontology

### ISSUE THREAD

**Issue by marijane** [data2health/credit-ontology#7]
As I'm reading up on how to set up a w3id, I realized that there are a couple options to consider for the persistent URL for this ontology.  Here is what I'm considering...

Use the same slug as the GitHub repo:  https://w3id.org/credit-ontology
Use a nested/patterned URL strategy:  https://w3id.org/credit/ontology

I find the second appealing because it feels more elegant.  It would allow setting up multiple redirects, for example we could point https://w3id.org/credit/taxonomy at the casrai dictionary entry for the taxonomy, if that's something we would want to do.

**Comment by marijane** [comment]
@mellybelly Do you have an opinion on this?

**Comment by mellybelly** [comment]
@jmcmurry any advice?

**Comment by jmcmurry** [comment]
Nesting in this case is OK, provided your documentation is crystal clear and you select corresponding prefixes for each of the type-specific paths when doing the curie expansion / contraction. Also, you might do well to have the local IDs have dedicated numeric ranges that not overlap, just to guard against collision (since someone could easily confuse creditont:1001 with credittax:1001 and think that they were referring to the same class).

**Comment by marijane** [comment]
Thank you, Julie.  Since I'd be linking to CASRAI's documentation of the taxonomy for the nested taxonomy link, there's no issue with curies, since they don't use a linked data implementation.

**Comment by marijane** [comment]
Talked with @mellybelly, we are going to use the nested form.

**Comment by marijane** [comment]
Submitted pull request to w3id repo today!
